### PR TITLE
I made a README 

### PR DESCRIPTION
**Pull request by mjbrender**
.. that is almost as pretty as `omglog`. Let me know if you'd like any updates before merge and **thank you** for this beautiful gem :+1:

### CODE REVIEW

**Comment by mjbrender** [comment]
Hey @benhoskings - lmk if you'd like any details to change before a merge. Thanks again for making this gem.

**Comment by benhoskings** [comment]
Thanks and sorry for delaying. I haven't been watching github.

I'm happy to merge your commits as they stand, but I hope you don't mind if I rewrite it into my own words! (I might change the screenshot to one of omglog itself too.)

**Comment by mjbrender** [comment]
Hey @benhoskings - of course! I just wanted to add some context to a great gem. Feel free to make it your own :+1:

**Comment by mattnichols** [comment]
This gem is in need of a README! This should be merged. :+1:

**Comment by benhoskings** [comment]
I've finally added a simple readme of my own; thanks for your PR all the same.

**Comment by mjbrender** [comment]
You bet @benhoskings! Love the work and glad to help.

**Pull request closed without merging**
